# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awls < Formula
  desc ""
  homepage ""
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/danpilch/awls/releases/download/v0.1.1/awls_0.1.1_darwin_amd64.tar.gz"
    sha256 "f0c98c46ffcad3f1a6c41989ced66d0ea612bc7ea6848025f3f1d4eb79ca1bcd"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/danpilch/awls/releases/download/v0.1.1/awls_0.1.1_darwin_arm64.tar.gz"
    sha256 "a4a581a2e5ac459095ba095541aa7bfabc54def8437dfc43d2469f6bea6f42da"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/danpilch/awls/releases/download/v0.1.1/awls_0.1.1_linux_amd64.tar.gz"
    sha256 "7308e480976dbdd3bb71309a752f75c255c4d1af35b3b76ef877e5416e453d08"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/danpilch/awls/releases/download/v0.1.1/awls_0.1.1_linux_arm64.tar.gz"
    sha256 "d9e706a95e0a46a5833bfe53826edfca62440832a655449321bc0b0177691059"
  end

  def install
    bin.install "awls"
  end
end
